### ISSUE TITLE
Voice information

### ISSUE THREAD

**Issue by Olebeh** [neplextech/canvacord#119]
Can information about how many hours the user has spent for the vc be displayed in the rank card?

**Comment by DevAndromeda** [comment]
@Olebeh what exactly is voice information supposed to be? The rank card works with current xp & required xp values. What exactly do you expect from voice information?

**Comment by Olebeh** [comment]
@DevAndromeda voice information is field that shows how many time have you been in voice channels in this guild, ![here's an example](https://user-images.githubusercontent.com/71090478/180632203-fcc401f2-0079-446c-82a4-aa9108808f51.png)

**Comment by Olebeh** [comment]
Still relevant?

**Comment by skdhg** [comment]
> Still relevant?

Yes
