### ISSUE TITLE
add circle and width in setCustomStatusColor methode

### ISSUE THREAD

**Issue by FabienBounoir** [neplextech/canvacord#140]
to change circle type and width size, I want to use .setStatus and after use setCustomStatusColor while I don't want to have a normal status at all. 

Before:
/**
     * Set custom status color
     * @param {string} color Color to set
     * @returns {Rank}
     */
    setCustomStatusColor(color) {
        if (!color || typeof color !== "string") throw new Error("Invalid color!");
        this.data.status.color = color;
        return this;
    }
    
    After:
    /**
     * Set custom status color
     * @param {string} color Color to set
     * @param {boolean} circle If status icon should be circular.
     * @param {number|boolean} width Status width
     * @returns {Rank}
     */
        setCustomStatusColor(color, circle = false, width = 5) {
        if (!color || typeof color !== "string") throw new Error("Invalid color!");
        this.data.status.color = color;
        
        if (width !== false) this.data.status.width = typeof width === "number" ? width : 5;
        else this.data.status.width = false;
        if ([true, false].includes(circle)) this.data.status.circle = circle;

        return this;
    }

**Comment by archaeopteryx1** [comment]
could you explain a bit more please?

**Comment by FabienBounoir** [comment]
It is very redundant to make a .setStatus(...) and then a .setCustomStatusColor(...) so that you can have set if you want the circle and size.

Basically if you want a custom colour with a different size you first have to do .setStatus("online", true, 30) and then do .setCustomStatusColor(#7D4E57)

I think it would be wise to add the circle and width arguments directly to the .setCustomStatusColor(...) method to avoid entering .setStatus(...)

Before change:
Canvacard.Rank().setStatus("online", true, 30).setCustomStatusColor(#7D4E57)

with change:
Canvacard.Rank().setCustomStatusColor(#7D4E57, true, 30)
