### ISSUE TITLE
Freedom in setDiscriminator usage

### ISSUE THREAD

**Issue by yash1441** [neplextech/canvacord#143]
Would be really helpful if setDiscriminator had more freedom. Custom length, alphanumeric, etc.

**Comment by skdhg** [comment]
https://github.com/neplextech/canvacord/releases/tag/v5.4.9

**Comment by yash1441** [comment]
Looks great!

Although, I was looking more into the possibility to set the discriminator like "#abc3d" and not just "abc3d" which attaches "@" automatically to it. This will allow more use cases to the library apart from discord usernames, for example my use case is for Valorant rank card which have usernames like "ABCD1234#A1B2".

**Comment by skdhg** [comment]
> Looks great!
> 
> Although, I was looking more into the possibility to set the discriminator like "#abc3d" and not just "abc3d" which attaches "@" automatically to it. This will allow more use cases to the library apart from discord usernames, for example my use case is for Valorant rank card which have usernames like "ABCD1234#A1B2".

sure, next version

**Comment by twlite** [comment]
please migrate to v6 for full customization
