### ISSUE TITLE
Can i change border color of rank card?

### ISSUE THREAD

**Issue by Deagarys** [neplextech/canvacord#153]
![image](https://user-images.githubusercontent.com/37025496/235121848-1ecd83cd-c462-4988-9604-c04ed4f4d0c8.png)
Would love to change that ugly grey color

**Comment by skdhg** [comment]
The border you are talking about seems to be the background image you are using. I have attached a sample image with different background.

![image](https://user-images.githubusercontent.com/46562212/235314229-9220ad43-e540-45ab-9bc8-a742c9053416.png)

**Comment by skdhg** [comment]
> When i use the background image i get the borders around the image, How did you manage to change the borders? could you send a code snippit?

There isnt any issue, it's just the background image you are using. Try using a different background image.

**Comment by twlite** [comment]
please switch to v6 for full customization
