### ISSUE TITLE
assets issue

### ISSUE THREAD

**Issue by twlite** [neplextech/canvacord#157]
To those who are having weird issues like text and images (getting errors such as `unsupported image source` or similar) not appearing properly (as shown in the image below), it is because the assets were not correctly built on your system.

![image](https://github.com/neplextech/canvacord/assets/46562212/a6319ae4-f7a5-41db-8111-1ed610d16829)

To fix this issue, execute the following command on your terminal

```sh
$ npx canvacord rebuild --force
```

This will rebuild all of the assets from scratch which should fix the issue.

**Comment by 21Z** [comment]
reopen #158
