### ISSUE TITLE
[BUG]: Welcomer text not showing...

### ISSUE THREAD

**Issue by 21Z** [neplextech/canvacord#158]
I've seen several reports in the (CesiumLabs) server saying that the text in welcomer doesnt display, testing the code they used, i can only reproduce this on windows, so its probably a font issue...

Code i used:
```js
const member = msg.member
const {Welcomer} = require("canvacord");
const welcimg = new Welcomer()
        .setAvatar(member.user.displayAvatarURL({ dynamic: false, extension: "png" }))
        .setUsername(member.user.username)
        .setDiscriminator(member.user.discriminator)
        .setGuildName(member.guild.name)
        .setMemberCount(member.guild.memberCount + 1)
.setBackground("https://cdn.discordapp.com/attachments/1103704135049674775/1113066551692771359/56baae6240862cbf8090eb031c9eda5b.png");
welcimg.build().then(m => {
 msg.channel.send({ files: [m] }); 
})
```

Windows:
![image](https://github.com/neplextech/canvacord/assets/69188068/5fe7282b-71f4-4442-a5d4-792c4acebc4f)
Linux:
![image](https://github.com/neplextech/canvacord/assets/69188068/5d34e81c-910e-4882-b1ec-dc6ebd97b289)

**Comment by skdhg** [comment]
this issue is related to assets, see https://github.com/neplextech/canvacord/issues/157 for a fix

**Comment by 21Z** [comment]
> this issue is related to assets, see #157 for a fix

I tried that already, doesn't seem to work.
checked it again now after the reply, still doesn't work...
