### ISSUE TITLE
[bug] Username tag is very offset

### ISSUE THREAD

**Issue by Miniontoby** [neplextech/canvacord#162]
Hi,

I saw the test file used the discriminator field for the new username thingy so I added a check if the discriminator is 0 and then use the username, but what happens is that the username thingy is very offset to the left, see here:

![card](https://media.discordapp.net/attachments/1113535958105739264/1121497365120028852/file.jpg)

Version: 5.4.10

Please fix it

- Miniontoby

**Comment by twlite** [comment]
please switch to v6
