### ISSUE TITLE
optionally remove online-offline status

### ISSUE THREAD

**Issue by Narkeus2230** [neplextech/canvacord#184]
Even though we removed the setting (`.setStatus`), the online status section is still there. If the status is not set, the online-offline status should be removed from the side of the profile.

![rankcard](https://github.com/neplextech/canvacord/assets/75725922/a8b0109f-5d55-4847-92eb-4948841e6515)

It would also be perfect if the font size was a few pixels larger and the user profile picture a little bigger.

**Comment by twlite** [comment]
done
