### ISSUE TITLE
Error: No fonts are loaded.

### ISSUE THREAD

**Issue by beepboopdai** [neplextech/canvacord#198]
`const rank = new canvacord.RankCardBuilder()
      .setAvatar(targetUserObj.user.avatarURL({ size: 256 }))
      .setRank(currentRank)
      .setLevel(fetchedLevel.level)
      .setCurrentXP(fetchedLevel.xp)
      .setRequiredXP(calculateLevelXp(fetchedLevel.level))
      .setStatus(targetUserObj.presence.status)
      .setUsername(targetUserObj.user.username)
      .setFonts("Arial")`
      
i was trying to run this code but everytime i run the command i just get "Error: No fonts are loaded."

**Comment by TomasSlekys** [comment]
I'm facing the same issue

**Comment by twlite** [comment]
@TomasSlekys @beepboopdai You need to manually register at least one font in v6. Place the following at the top of your file and make sure it only runs *once* to prevent memory leaks.

```
// loads the bundled "Geist" font
require('canvacord').Font.loadDefault()
```
